# Docker Compose para  Herederos de Consalud
# Ejecutar con: docker-compose up <servicio>

services:
  # DESARROLLO - Para trabajar en la aplicación
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: app-herederos-dev
    ports:
      - "5173:5173"  # la app estará en http://localhost:5173
    volumes:
      - .:/app                    # Sincroniza tu código
      - /app/node_modules         # Optimiza node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0        # Permite acceso externo
    restart: unless-stopped
    # Comando: docker-compose up app

  # PRODUCCIÓN - Para deploy real
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: app-herederos-prod
    ports:
      - "3000:3000"              # Tu app estará en http://localhost:3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - production
    # Comando: docker-compose --profile production up app-prod

  # TESTING - Para pruebas
  app-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: development        # Usa desarrollo pero con configuración de test
    container_name: app-herederos-test
    ports:
      - "4173:5173"             # Puerto diferente para no conflictos
    environment:
      - NODE_ENV=test
      - VITE_HOST=0.0.0.0
    restart: unless-stopped
    profiles:
      - test
    # Comando: docker-compose --profile test up app-test

# Volúmenes nombrados para optimización
volumes:
  node_modules:
  npm_cache:

# Red personalizada (opcional)
networks:
  consalud-network:
    driver: bridge