# Docker Compose para  Herederos de Consalud
# Ejecutar con: docker-compose up <servicio>

services:
  # DESARROLLO - Para trabajar en la aplicación
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app-gestor-solicitudes-dev
    ports:
      - "5173:5173"  # la app estará en http://localhost:5173
    volumes:
      - .:/app                   
      - /app/node_modules        
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0        # Permite acceso externo
    restart: unless-stopped
    # Comando: docker-compose up app

  # PRODUCCIÓN - Para deploy real
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app-gestor-solicitudes-prod
    ports:
      - "3000:3000"              # la app estará en http://localhost:3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - production

  # TESTING - Para pruebas
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: app-gestor-solicitudes-test
    ports:
      - "4173:5173"             
    environment:
      - NODE_ENV=test
      - VITE_HOST=0.0.0.0
    restart: unless-stopped
    profiles:
      - test

# Volúmenes nombrados para optimización
volumes:
  node_modules:
  npm_cache:

# Red personalizada 
networks:
  consalud-network:
    driver: bridge