# Etapa base con Alpine
FROM node:20-alpine AS base

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    && ln -sf python3 /usr/bin/python

WORKDIR /app

# Copiar archivos de dependencias y el core tgz
COPY package*.json ./
COPY ./consalud-core-1.0.0.tgz ./

# Instalar dependencias de desarrollo
RUN npm ci --no-audit --no-fund && npm cache clean --force

# Copiar el resto del código fuente
COPY . .

# Crear usuario no-root
RUN addgroup -g 1001 -S reactgroup && \
    adduser -S reactuser -u 1001 -G reactgroup && \
    chown -R reactuser:reactgroup /app
USER reactuser

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"] 