services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-gerederos
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development