# Etapa base con Alpine
FROM node:20-alpine AS base

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    && ln -sf python3 /usr/bin/python

WORKDIR /app

# Copiar archivos de dependencias y el core tgz
COPY package*.json ./
COPY ./consalud-core-1.0.0.tgz ./
COPY .env.test ./.env.test

# Instalar dependencias de desarrollo
RUN npm ci --no-audit --no-fund && npm cache clean --force

# Copiar el resto del código fuente
COPY . .

# Ejecutar los tests
CMD ["npm", "run", "test"] 