apiVersion: v1
kind: Service
metadata:
  name: app-gestor-solicitudes-service
spec:
  selector:
    app: app-gestor-solicitudes
  ports:
    - protocol: TCP
      port: 80         # Puerto interno del cluster
      targetPort: 80 # Puerto donde escucha el contenedor
  type: ClusterIP
